### ISSUE TITLE
“args” in “execute_program” can take only one argument

### ISSUE THREAD

**Issue by komagen** [crond-jaist/cyris#1]
“args” in “execute_program” in the **-range.yml file seems can take only one argument

I found this when I tried to execute a shell script on VM.
As a result I succeeded by as follows:
**-range.yml : 
    tasks:
    - copy_content:
      - src: /home/cyuser/vm_setting/args.sh
        dst: /tmp/
    - execute_program:
      - program: .
        args: /tmp/args.sh
        interpreter: bash

args.sh : 
#!/bin/bash
touch /tmp/test

I checked by as follows:
NG:(Can “args” take some args?)
**-range.yml:
    - execute_program:
      - program: ls
        args: -al >> /tmp/test
        interpreter: bash

NG:(How can I run shell script?)
**-range.yml
    - copy_content:
      - src: /home/cyuser/vm_setting/args.sh
        dst: /tmp/
    - execute_program:
      - program: /tmp/args.sh
        interpreter: bash

NG:(“args” must be?)
    tasks:
    - copy_content:
      - src: /home/cyuser/vm_setting/args.sh
        dst: /tmp/
    - execute_program:
      - program: /tmp/args.sh
        args: dummy
        interpreter: bash

At the NG situation, I could see this message in cytrone log:
* NOTE: cyris: The warning below can be safely ignored (caused by use of paramiko library in 'clone_environment.py').
/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
  self._cipher = factory.new(key, *args, **kwargs)

**Comment by crond-jaist** [comment]
Sorry for the late reply, we somehow missed your issue. The 'args' issue is hopefully solved in the latest release (and there are also some workarounds for it), so let us know if you still have problems after trying CyRIS v1.1.
As for the message you mentioned at the end, it can be ignored (as the message itself says), and is related to the paramiko library in Python, hence not related to your issue. (This warning is actually not present if you use Ubuntu 18.04 LTS.)
