### ISSUE TITLE
Where is the "basevm_small.xml"?

### ISSUE THREAD

**Issue by yonggo111111** [crond-jaist/cyris#3]
I can't find the file while  README file refers to.

**Comment by athna** [comment]
basevm_small.xml is included CyRIS v0.2's assets ( basevm_small.tar.gz ).
but recommend to use CyRIS 1.0's assets ( basevm.tar.gz ).
and can download from release pages.

**Comment by yonggo111111** [comment]
Thanks for your reply,  the problem solved.
