### ISSUE TITLE
A question about logging in to CyRIS

### ISSUE THREAD

**Issue by forever-in18** [crond-jaist/cyris#8]
Dear Razvan,
I created CyRIS with ubuntu20.04, but I cannot log in with my account password, as shown below:
ssh: connect to host xxx port xxx: Connection refused
If you have time, I hope to help me out.
Best,
Jason.

**Comment by crond-jaist** [comment]
Hi Jason,

Do you mean to say that you cannot log in anymore into the host on which you installed CyRIS?! This shouldn't be related to CyRIS, so you should check what else you did that prevents you from logging in.

If you are talking about logging in the cyber range created by CyRIS, the log in information is written in the file "range_notification.txt" located in the cyber range directory. You should use that information to log in to the cyber range, not your account password.

I hope this helps, but if you need more support you should explain your problem in as much detail as possible, as we have no knowledge of your setup.

Best wishes,
Razvan

**Comment by forever-in18** [comment]
Hi&nbsp;Razvan，
Thank you very much for your reply. I used the "range_notification.txt" file: to log in to the created CyRIS, but I encountered:


So how should I solve this problem?
Thanks agin.
Best wishes,
Jason&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crond-jaist/cyris"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 上午10:07
收件人:&nbsp;"crond-jaist/cyris"<cyris@noreply.github.com&gt;;
抄送:&nbsp;"syg1314"<945704550@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crond-jaist/cyris] A question about logging in to CyRIS (#8)





 
Hi Jason,
 
Do you mean to say that you cannot log in anymore into the host on which you installed CyRIS?! This shouldn't be related to CyRIS, so you should check what else you did that prevents you from logging in.
 
If you are talking about logging in the cyber range created by CyRIS, the log in information is written in the file "range_notification.txt" located in the cyber range directory. You should use that information to log in to the cyber range, not your account password.
 
I hope this helps, but if you need more support you should explain your problem in as much detail as possible, as we have no knowledge of your setup.
 
Best wishes,
 Razvan

**Comment by crond-jaist** [comment]
I see. In principle the problem you are reporting should not happen if the range is created successfully, so I guess there may be some hidden problem with cyber range creation. I suggest you use the command `virsh list` to see the IDs of active virtual machines, and then `virsh console <ID>` to connect to the one you created. Hopefully you can then investigate by yourself what the issue may be.
Razvan

**Comment by forever-in18** [comment]
I see.Thanks a lot for your help!
Jason
